# https://pre-commit.com
default_install_hook_types: [commit-msg, pre-commit]
default_stages: [pre-commit, manual]
fail_fast: true
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        types: [python]
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: trailing-whitespace
        types: [python]
  - repo: local
    hooks:
      - id: uv-lock-check
        name: uv lock check
        entry: uv
        args: ["lock", "--check"]
        require_serial: true
        language: system
        pass_filenames: false
      - id: ruff-check
        name: ruff check
        entry: uv
        args: ["run", "--directory", "apps/api", "ruff", "check", "--force-exclude", "--extend-fixable=ERA001,F401,F841,T201,T203", "--fix-only", "src", "tests"]
        require_serial: true
        language: system
        pass_filenames: false
      - id: ruff-format
        name: ruff format
        entry: uv
        args: ["run", "--directory", "apps/api", "ruff", "format", "--force-exclude", "src", "tests"]
        require_serial: true
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: uv
        args: ["run", "--directory", "apps/api", "mypy", "src"]
        language: system
        pass_filenames: false
