site_name: Fridge App Backend API Documentation
site_description: API documentation for the Fridge App Backend project.
site_url: https://rchretien.github.io/fridge-app
repo_url: https://github.com/rchretien/fridge-app
repo_name: rchretien/fridge-app

theme:
  name: material

nav:
  - Home: index.md

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
